#!/usr/bin/env bash
echo "== Create Bucket"

if [ -z "$1" ]; then
    echo "There needs to be a bucket name. e.g. ./bucket my-bucket-name"
    exit 1
fi
BUCKET_NAME=$1

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration="LocationConstraint=eu-west-2" \
--query Location \
--output text

# ./s3/bash-scripts/create-bucket my-new-shiny-bucket-ab12345