#!/usr/bin/env bash
echo "== Delete Bucket"

if [ -z "$1" ]; then
    echo "There needs to be a bucket name. e.g. ./bucket my-bucket-name"
    exit 1
fi
BUCKET_NAME=$1

aws s3api delete-bucket \
--bucket $BUCKET_NAME \

# ./s3/bash-scripts/delete-bucket my-new-shiny-bucket-ab12345