#!/usr/bin/env bash
echo "== List Objects"

if [ -z "$1" ]; then
    echo "There needs to be a bucket name. e.g. ./bucket my-bucket-name"
    exit 1
fi
BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \

# ./s3/bash-scripts/list-objects my-new-shiny-bucket-ab12345